import React from "react";
import {
  View,
  Text,
  ScrollView,
  Pressable,
  Alert,
  TouchableOpacity,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import tailwind from "twrnc";
import { useTheme } from "../context/ThemeContext";
import { useTour } from "../context/TourContext";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Ionicons } from "@expo/vector-icons";
import * as FileSystem from "expo-file-system/legacy";

const TourList = ({ navigation }) => {
  const { isDarkMode } = useTheme();
  const { tours, deleteTour, calculateSettlement } = useTour();

  const handleDelete = (id) => {
    Alert.alert("Delete Tour", "Are you sure you want to delete this tour?", [
      { text: "Cancel", style: "cancel" },
      {
        text: "Delete",
        style: "destructive",
        onPress: () => deleteTour(id),
      },
    ]);
  };

  const handlePdf = async (tour) => {
    try {
      const members = tour.members || [];
      const expenses = tour.expenses || [];
      const settlements = calculateSettlement(tour.id);
      const fileName = `FinSmart_Tour_Report_${tour.name.replace(/\s+/g, "_")}_${new Date().toISOString().slice(0, 10)}.pdf`;
      const membersRows = members
        .map(
          (m) => `
<tr>
<td>${m.name}</td>
<td>Tk ${m.paid || 0}</td>
</tr>
`,
        )
        .join("");

      const expensesRows = expenses
        .map(
          (e) => `
<tr>
<td>${e.title}</td>
<td>Tk ${e.amount}</td>
</tr>
`,
        )
        .join("");

      const settlementRows = settlements
        .map(
          (s) => `
<tr>
<td><b>${s.from}</b> should pay <b>${s.to}</b></td>
<td>Tk ${s.amount}</td>
</tr>
`,
        )
        .join("");

      const html = `
<html>
<head>
<style>

body{
font-family:Arial;
padding:20px;
color:#111;
}

h1{
text-align:center;
margin-bottom:20px;
}

.summary{
background:#f1f5f9;
padding:15px;
border-radius:8px;
margin-bottom:20px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
margin-bottom:20px;
}

th{
background:#6366f1;
color:white;
padding:10px;
text-align:left;
}

td{
padding:10px;
border-bottom:1px solid #e5e7eb;
}

tr:nth-child(even){
background:#f9fafb;
}

.footer{
margin-top:30px;
text-align:center;
font-size:12px;
color:#6b7280;
}

</style>
</head>

<body>

<h1>Tour Report</h1>

<p><b>Tour:</b> ${tour.name}</p>
<p><b>Destination:</b> ${tour.destination}</p>
<p><b>Date:</b> ${
        tour.createdAt ? new Date(tour.createdAt).toLocaleDateString() : ""
      }</p>

<div class="summary">
<p><b>Total Expense:</b> Tk ${tour.totalExpense || 0}</p>
<p><b>Per Person:</b> Tk ${tour.perPerson || 0}</p>
</div>

<h2>Members</h2>

<table>
<tr>
<th>Name</th>
<th>Paid</th>
</tr>
${membersRows}
</table>

<h2>Expenses</h2>

<table>
<tr>
<th>Title</th>
<th>Amount</th>
</tr>
${expensesRows}
</table>

<h2>Settlement</h2>

<table>
<tr>
<th>Payment</th>
<th>Amount</th>
</tr>
${settlementRows}
</table>

<div class="footer">
Generated By FinSmart
</div>

</body>
</html>
`;

      const { uri } = await Print.printToFileAsync({ html });

      const newPath = FileSystem.documentDirectory + fileName;

      await FileSystem.moveAsync({
        from: uri,
        to: newPath,
      });

      await Sharing.shareAsync(newPath, {
        mimeType: "application/pdf",
      });
    } catch (err) {
      Alert.alert("Error", "Failed to generate PDF");
    }
  };

  return (
    <SafeAreaView
      style={[
        tailwind`flex-1`,
        { backgroundColor: isDarkMode ? "#020617" : "#f8fafc" },
      ]}
    >
      <ScrollView contentContainerStyle={tailwind`p-6 pb-28`}>
        <View style={tailwind`mb-6`}>
          <Text
            style={[
              tailwind`text-3xl font-bold`,
              { color: isDarkMode ? "#fff" : "#000" },
            ]}
          >
            My Tours
          </Text>

          <Text
            style={[
              tailwind`mt-2`,
              { color: isDarkMode ? "#94a3b8" : "#6b7280" },
            ]}
          >
            Track and manage your tour expenses
          </Text>
        </View>

        {!tours || tours.length === 0 ? (
          <View style={tailwind`mt-20 items-center`}>
            <Text style={tailwind`text-slate-400 text-lg`}>No Tours Yet</Text>

            <Text style={tailwind`text-slate-500 mt-2 text-center`}>
              Create your first tour to start tracking expenses
            </Text>
          </View>
        ) : (
          tours.map((tour, index) => {
            const members = tour.members?.length || 0;
            const total = tour.totalExpense || 0;
            const perPerson = members > 0 ? Math.ceil(total / members) : 0;

            const date = tour.createdAt
              ? new Date(tour.createdAt).toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "short",
                  year: "numeric",
                })
              : "";

            return (
              <View
                key={`${tour.id}-${index}`}
                style={[
                  tailwind`p-5 rounded-2xl mb-5`,
                  {
                    backgroundColor: isDarkMode ? "#0f172a" : "#ffffff",
                  },
                ]}
              >
                <Pressable
                  onPress={() =>
                    navigation.navigate("TourDetails", {
                      tourId: tour.id,
                    })
                  }
                  onLongPress={() => handleDelete(tour.id)}
                >
                  <View style={tailwind`flex-row justify-between items-center`}>
                    <Text
                      style={[
                        tailwind`text-xl font-bold`,
                        { color: isDarkMode ? "#fff" : "#000" },
                      ]}
                    >
                      {tour.name}
                    </Text>

                    <Text
                      style={[
                        tailwind`text-xs`,
                        { color: isDarkMode ? "#94a3b8" : "#6b7280" },
                      ]}
                    >
                      {date}
                    </Text>
                  </View>

                  <Text style={tailwind`text-slate-400 mt-1`}>
                    📍 {tour.destination}
                  </Text>

                  <Text style={tailwind`text-slate-400 mt-1`}>
                    👥 {members} Members
                  </Text>

                  <Text style={tailwind`text-sky-500 mt-2 font-semibold`}>
                    Total: Tk {total}
                  </Text>

                  <Text style={tailwind`text-orange-400`}>
                    Per Person: Tk {perPerson}
                  </Text>

                  <View style={tailwind`mt-2`}>
                    <Text
                      style={[
                        tailwind`font-semibold`,
                        {
                          color:
                            tour.status === "Settled" ? "#22c55e" : "#f59e0b",
                        },
                      ]}
                    >
                      {tour.status || "Ongoing"}
                    </Text>
                  </View>
                </Pressable>

                <TouchableOpacity
                  onPress={() => handlePdf(tour)}
                  style={tailwind`mt-4 bg-indigo-500 py-3 rounded-xl items-center`}
                >
                  <Text style={tailwind`text-white font-bold`}>
                    Download PDF
                  </Text>
                </TouchableOpacity>
              </View>
            );
          })
        )}
      </ScrollView>
    </SafeAreaView>
  );
};

export default TourList;
