export const CATEGORIES = [
  { id: 1, name: "Food", icon: "🍔", color: "#F59E0B" },
  { id: 2, name: "Bills/Utilities", icon: "💡", color: "#FB7185" },
  { id: 3, name: "Family", icon: "👨‍👩‍👧‍👦", color: "#22C55E" },
  { id: 4, name: "Healthcare", icon: "🏥", color: "#EF4444" },
  { id: 5, name: "Fuel", icon: "⛽", color: "#F97316" },
  { id: 6, name: "Phone/Internet", icon: "📱", color: "#3B82F6" },
  { id: 7, name: "Education", icon: "🎓", color: "#8B5CF6" },
  { id: 8, name: "Entertainment", icon: "🎬", color: "#EC4899" },
  { id: 9, name: "Shopping", icon: "🛍️", color: "#D946EF" },
  { id: 10, name: "Travel", icon: "✈️", color: "#06B6D4" },
  { id: 11, name: "Socializing", icon: "🍻", color: "#A16207" },
  { id: 12, name: "Withdrawal", icon: "🏧", color: "#64748B" },
  { id: 13, name: "Transfer", icon: "🔁", color: "#10B981" },
  { id: 14, name: "Transportation", icon: "🚗", color: "#0EA5E9" },
  { id: 15, name: "Housing", icon: "🏠", color: "#6366F1" },
  { id: 16, name: "Miscellaneous", icon: "📦", color: "#475569" },
];
